In [1]:
import datetime, os
import pandas as pd

In [2]:
# Clean Flu data, sort_values('date')
flu_df = pd.read_csv('../data/flu_data.csv').sort_values('date')
flu_df.isna().sum()

date                      0
Texas                     0
Louisiana                 0
Washington                0
New Jersey                0
Arkansas                  0
Montana                   0
North Dakota              0
Virgin Islands           52
Nebraska                  0
New Mexico                0
Indiana                   0
California                0
Ohio                      0
South Carolina            0
Puerto Rico             156
Rhode Island              0
Michigan                  0
Georgia                   0
Wyoming                   0
Hawaii                    0
New Hampshire             0
Maryland                  0
Mississippi               0
Connecticut               0
West Virginia             0
Iowa                      0
Illinois                  0
Vermont                   0
Tennessee                 0
Missouri                  0
Wisconsin                 0
North Carolina            0
Pennsylvania              0
Kentucky                  0
Delaware                  0
Kansas                    0
Oregon                    0
Massachusetts             0
Alabama                   0
Alaska                    0
Arizona                   0
Minnesota                 0
Maine                     0
Nevada                    0
Idaho                     0
Utah                      0
Virginia                  0
New York                  0
District of Columbia      0
Oklahoma                  0
South Dakota              0
New York City             0
Colorado                  0
dtype: int64

In [3]:
flu_df = flu_df.drop(['Virgin Islands', 'Puerto Rico', 'New York City'], 1)
print(flu_df.shape)

flu_df.to_csv('../data/clean_flu_data.csv', index = None)
flu_df.tail(20)

(461, 51)

,date,Texas,Louisiana,Washington,New Jersey,Arkansas,Montana,North Dakota,Nebraska,New Mexico,...,Maine,Nevada,Idaho,Utah,Virginia,New York,District of Columbia,Oklahoma,South Dakota,Colorado
433,2019-12,5.79463,5.47045,3.772620,4.06803,4.832290,2.263490,2.788740,2.414020,3.801210,...,3.006700,2.406210,1.775570,4.03966,5.211840,3.259890,2.72061,4.805580,1.355030,4.748190
434,2019-13,4.89506,4.76415,2.338980,3.69940,3.505660,1.988540,2.010180,2.604170,2.804290,...,2.589040,2.173910,2.345160,3.41714,4.392670,2.751860,2.64005,3.450830,1.392370,3.694140
435,2019-14,4.40566,4.03481,1.469510,3.44312,2.739730,1.239890,2.421170,2.514890,2.442830,...,2.405570,1.856130,1.054590,3.27877,3.750110,2.750080,0.88734,2.969360,1.210890,3.619880
436,2019-15,3.94129,3.49741,0.857093,3.20178,1.899710,1.138750,1.548420,2.064930,2.336040,...,2.103370,1.408310,0.664894,2.35355,2.816660,2.087780,2.10634,1.944510,0.870133,3.093720
437,2019-16,3.42261,3.08857,0.706952,2.65269,1.748420,0.886171,1.403890,1.886570,2.125430,...,1.838030,1.214730,0.309837,2.73766,2.162770,1.767580,1.44346,1.818660,0.962503,2.888540
438,2019-17,2.70961,2.92558,0.411100,2.51062,1.412740,0.852827,0.997151,1.516360,1.676290,...,1.413020,1.208580,0.712589,2.31013,1.777840,1.261390,1.81048,1.463720,0.798122,2.612120
439,2019-18,2.55929,2.49976,0.555024,2.35408,1.549370,0.662583,1.080950,1.589910,1.491810,...,1.338730,1.139940,0.789889,2.42628,1.581500,1.154040,1.81989,1.115920,0.658073,2.846530
440,2019-19,2.50535,2.44035,0.509580,2.14652,1.327430,0.699205,0.718804,1.558380,1.254130,...,1.094400,0.930651,0.774103,2.32142,1.558330,0.898734,1.79616,1.022870,0.651997,2.610700
442,2019-20,2.50115,2.69518,0.383632,2.33124,1.449280,0.830827,0.838518,1.284230,1.365440,...,1.167290,0.927070,0.214900,2.33507,1.611960,0.835082,1.57009,0.991205,0.520999,2.587580
443,2019-21,2.90345,2.46884,0.507731,2.19421,1.193890,0.822529,1.975680,1.434740,1.110850,...,0.949391,1.084310,0.197824,2.01746,1.529420,0.899005,1.84905,1.210140,0.708676,2.488740
444,2019-22,2.22547,2.33244,0.597558,2.28107,0.884173,0.676841,1.094030,1.368080,1.115030,...,0.957515,0.910332,0.286123,2.43707,1.453980,0.918499,1.61440,0.663885,0.000100,2.128780
445,2019-23,2.21661,2.08549,0.543607,1.98396,1.674480,0.751001,1.402740,1.093190,0.907921,...,0.843117,1.008920,0.274725,2.11268,1.388150,0.799747,1.71763,0.495634,0.667170,2.141000
446,2019-24,2.26458,1.81931,0.342827,2.03344,1.159420,0.645876,0.363526,1.096680,0.821718,...,0.704935,0.933738,0.000100,1.69391,1.226630,0.669141,1.41348,0.873447,0.394452,1.752540
447,2019-25,1.97300,1.78423,0.260213,1.78061,0.626959,0.418702,0.761267,1.029290,0.665227,...,0.612893,0.718940,0.000100,1.53606,1.161600,0.730797,4.60551,0.555257,0.431063,1.490570
448,2019-26,1.97842,1.82990,0.182959,1.78454,0.590319,0.356355,0.330430,0.896080,0.428147,...,0.562701,0.752071,0.000100,1.55616,1.034510,0.693126,1.32539,0.322841,0.443234,1.369450
449,2019-27,1.82690,1.78289,0.539926,1.79779,0.615385,0.504686,0.442087,1.006040,0.565824,...,0.604772,0.546315,0.000100,1.58535,0.927170,0.678007,3.95861,0.424056,0.360427,1.043860
450,2019-28,1.65596,1.85363,0.353838,1.61793,0.288184,0.538073,0.344234,0.773495,0.584795,...,0.558624,0.497344,0.000100,1.19744,0.900846,0.607034,4.21128,0.361664,0.503960,0.959798
451,2019-29,1.49702,1.73031,0.265041,1.43867,0.727069,0.478878,0.164783,0.987686,0.572213,...,0.448547,0.588998,0.000100,1.31394,0.870202,0.494300,4.04040,0.380417,0.368135,0.999950
453,2019-30,1.79673,1.76290,0.363840,1.32749,0.714286,0.437828,0.386100,1.047330,0.565417,...,0.511751,0.423831,0.000100,1.34406,0.800792,0.511351,3.19149,0.312256,0.316957,0.921444
454,2019-31,2.51025,1.74522,0.195914,1.37455,1.042750,0.385675,0.000100,0.823990,0.475490,...,0.349835,0.424152,0.000100,1.08701,0.786335,0.562652,4.34783,0.432900,0.379057,0.366407

In [4]:
def col_to_weeknum(df):
    df['date'] = pd.to_datetime(df['date'])
    week_num = df['date'].apply(lambda x: datetime.date(x.year, x.month, x.day).isocalendar()[1])
    df['date'] = [str(d.year) +'-'+ str(wn) for d,wn in zip(df['date'], week_num)]
    return df

def clean_google_df(state, to_return = False):
    df_google = pd.read_csv('../data/google/' + state + '.csv')
    print(df_google.shape)
    # Clean the date column if in wrong format
    if len(df_google.loc[0, 'date']) > 7:
        df_google = col_to_weeknum(df_google)
    
    all_dates = flu_df[['date']]
    clean_data = pd.merge(all_dates, df_google, how = 'left', on = 'date').fillna(method='backfill').fillna(method='ffill')
    assert clean_data.isna().sum().sum() == 0
    clean_data.to_csv('../data/google_clean/'+state+'.csv', index = None)
    if to_return:
        return clean_data

ny_google = clean_google_df('New York', True)
ny_google.head()

(120, 97)

,date,flu,treating flu,medicine for the flu,high fever,is the flu contagious,get over the flu,medicine for flu,how to get rid of the flu,fever cough,...,cold vs. flu,flu in children,do i have the flu,i have the flu,influenza incubation period,flu season,oscillococcinum,what is the flu,low body,remedies for the flu
0,2010-40,15.0,6.0,6.0,44.0,6.0,0.0,0.0,0.0,35.0,...,0.0,5.0,2.0,5.0,0.0,8.0,11.0,9.0,26.0,0.0
1,2010-41,15.0,6.0,6.0,44.0,6.0,0.0,0.0,0.0,35.0,...,0.0,5.0,2.0,5.0,0.0,8.0,11.0,9.0,26.0,0.0
2,2010-42,15.0,6.0,6.0,44.0,6.0,0.0,0.0,0.0,35.0,...,0.0,5.0,2.0,5.0,0.0,8.0,11.0,9.0,26.0,0.0
3,2010-43,15.0,6.0,6.0,44.0,6.0,0.0,0.0,0.0,35.0,...,0.0,5.0,2.0,5.0,0.0,8.0,11.0,9.0,26.0,0.0
4,2010-44,15.0,6.0,6.0,44.0,6.0,0.0,0.0,0.0,35.0,...,0.0,5.0,2.0,5.0,0.0,8.0,11.0,9.0,26.0,0.0

In [5]:
import os
all_states = [s[:-4] for s in os.listdir('../data/google/')]
for state in all_states:
    print(state)
    clean_google_df(state)

Georgia
(120, 97)
North Carolina
(120, 97)
Wyoming
(120, 49)
New Hampshire
(120, 96)
Wisconsin
(120, 98)
Minnesota
(120, 98)
Maryland
(120, 98)
Pennsylvania
(120, 96)
Texas
(120, 97)
Michigan
(120, 98)
Hawaii
(120, 81)
Tennessee
(120, 97)
District of Columbia
(120, 97)
Arkansas
(120, 96)
Ohio
(120, 97)
Nebraska
(120, 98)
Montana
(120, 93)
Indiana
(120, 97)
South Dakota
(120, 64)
Mississippi
(120, 94)
Connecticut
(120, 98)
Oklahoma
(120, 96)
Colorado
(120, 98)
Maine
(120, 97)
South Carolina
(120, 96)
North Dakota
(120, 60)
Louisiana
(120, 96)
Utah
(120, 97)
Virginia
(120, 98)
New York
(120, 97)
New Mexico
(120, 96)
Delaware
(120, 96)
Kentucky
(120, 96)
Massachusetts
(120, 98)
Alabama
(120, 96)
Arizona
(120, 97)
California
(120, 98)
Nevada
(120, 96)
Alaska
(120, 51)
Illinois
(120, 97)
Idaho
(120, 98)
Oregon
(120, 98)
Iowa
(120, 99)
Vermont
(120, 67)
West Virginia
(120, 98)
Kansas
(120, 98)
New Jersey
(120, 96)
Washington
(120, 99)
Missouri
(120, 98)
Rhode Island
(120, 98)